name: API_test
on:
  push:
    branches: [ main , develop ]
  pull_request:
    branches: [ main , develop ]

  workflow_dispatch:

jobs:
  integration:
    name: Integration test with newman
    runs-on: ubuntu-latest
    steps:
      - name: Setup newman
        run: sudo npm install -g newman
        
      - name: Setup jq
        run: sudo apt install jq
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image and run docker container
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        
      - name: Give permission to executables for test
        run: |
          sudo chmod +x ./newman_ci.sh
          sudo chmod +x ./rsa-sign/signing-cs
        working-directory: ./ci_tool
        
      - name: Sleep to wait for preparing of containers
        run: sleep 30
        
      - name: Run test shell script
        run: ./newman_ci.sh
        working-directory: ./ci_tool
