name: API_test
on:
  push:
    branches: [ main , develop ]
  pull_request:
    branches: [ main , develop ]

  workflow_dispatch:

jobs:
  integration:
    name: Integration test with newman
    runs-on: self-hosted
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup docker compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose
        working-directory: ./

      - name: Setup newman
        run: npm install -g newman
        
      - name: Setup jq
        run: sudo apt install jq
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image and run docker container
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d
        
      - name: Give permission to executables for test
        run: |
          sudo chmod +x ./newman_ci.sh
          sudo chmod +x ./rsa-sign/signing-cs
        working-directory: ./ci_tool
        
      - name: Sleep to wait for preparing of containers
        run: sleep 30
        
      - name: Run test shell script
        run: ./newman_ci.sh
        working-directory: ./ci_tool
