name: Docker
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: push docker image to registry
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_UNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Login to MISW docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.MISW_REGISTRY }}
          username: ${{ secrets.MISW_REGISTRY_USERNAME }}
          password: ${{ secrets.MISW_REGISTRY_PASSWORD }}

      - name: Create docker metadata
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: |
            ${{ secrets.REGISTRY }}/birdol/web
            ${{ secrets.MISW_REGISTRY }}/birdol/web
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest

      - name: build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile
          target: production
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Release
        run: |
          heroku container:login
          heroku container:release -a birdol web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
